@echo off
call echo Limpiando el Ambiente...
call cmd\killJava
call echo Compilando el proyecto...
call cmd\install
call echo Creando el paquete...
call cmd\package
call echo Ejecutando App...
call cmd\runJavaFX
call echo App ejecutada!
call echo #----------------------------------------#